// Array de objetos para la pagian contenidos

const contents = [
  {
    fc: "frontend",
    type: "html",
    title: "Etiquetas",
    description: "Elementos principales del lenguaje HTML.",
    id: "html-etiquetas",
  },
  {
    fc: "frontend",
    type: "html",
    title: "Códigos base",
    description: "Estructuras base para documentos HTML.",
    id: "html-codigos-base",
  },
  {
    fc: "frontend",
    type: "html",
    title: "Metadatos",
    description: "Información adicional sobre el documento HTML.",
    id: "html-metadatos",
  },
  {
    fc: "frontend",
    type: "html",
    title: "Importaciones",
    description: "Incorporar recursos externos en HTML.",
    id: "html-importaciones",
  },
  {
    fc: "frontend",
    type: "html",
    title: "Buenas prácticas",
    description: "Recomendaciones para escribir HTML limpio y eficiente.",
    id: "html-buenas-practicas",
  },

  {
    fc: "frontend",
    type: "css",
    title: "Importaciones",
    description: "Cómo incluir archivos CSS en un proyecto.",
    id: "css-importaciones",
  },
  {
    fc: "frontend",
    type: "css",
    title: "Selectores",
    description: "Formas de seleccionar elementos en CSS.",
    id: "css-selectores",
  },
  {
    fc: "frontend",
    type: "css",
    title: "Propiedad",
    description: "Definir características visuales con CSS.",
    id: "css-propiedad",
  },
  {
    fc: "frontend",
    type: "css",
    title: "Valor",
    description: "Especificar valores para propiedades CSS.",
    id: "css-valor",
  },
  {
    fc: "frontend",
    type: "css",
    title: "Comentarios",
    description: "Documentar código CSS con comentarios.",
    id: "css-comentarios",
  },
  {
    fc: "frontend",
    type: "css",
    title: "Reglas",
    description: "Conjuntos de selectores y declaraciones en CSS.",
    id: "css-reglas",
  },
  {
    fc: "frontend",
    type: "css",
    title: "Buenas prácticas",
    description: "Escribir CSS mantenible y eficiente.",
    id: "css-buenas-practicas",
  },

  {
    fc: "frontend, backend",
    type: "js",
    title: "Palabras reservadas",
    description: "Términos reservados en JavaScript.",
    id: "js-palabras-reservadas",
  },
  {
    fc: "frontend, backend",
    type: "js",
    title: "Comandos",
    description: "Instrucciones ejecutables en JavaScript.",
    id: "js-comandos",
  },
  {
    fc: "frontend, backend",
    type: "js",
    title: "Funciones",
    description: "Definición y uso de funciones en JavaScript.",
    id: "js-funciones",
  },
  {
    fc: "frontend, backend",
    type: "js",
    title: "CMV",
    description: "Conceptos de Closures, Modules y Variables en JavaScript.",
    id: "js-cmv",
  },
  {
    fc: "frontend, backend",
    type: "js",
    title: "DOM",
    description: "Manipulación del Document Object Model.",
    id: "js-dom",
  },
  {
    fc: "frontend, backend",
    type: "js",
    title: "Programación Modular",
    description: "Dividir el código en módulos reutilizables.",
    id: "js-programacion-modular",
  },
  {
    fc: "frontend, backend",
    type: "js",
    title: "Buenas Prácticas",
    description: "Recomendaciones para código limpio en JavaScript.",
    id: "js-buenas-practicas",
  },

  {
    fc: "frontend",
    type: "react",
    title: "Vite",
    description: "Configuración de proyectos React con Vite.",
    id: "react-vite",
  },
  {
    fc: "frontend",
    type: "react",
    title: "Componentes",
    description: "Creación y uso de componentes en React.",
    id: "react-componentes",
  },
  {
    fc: "frontend",
    type: "react",
    title: "Código Base",
    description: "Estructura inicial de un proyecto React.",
    id: "react-codigo-base",
  },
  {
    fc: "frontend",
    type: "react",
    title: "Buenas Prácticas",
    description: "Recomendaciones para proyectos React eficientes.",
    id: "react-buenas-practicas",
  },
  {
    fc: "frontend",
    type: "react",
    title: "Estructura de Archivos",
    description: "Organización de archivos en proyectos React.",
    id: "react-estructura-de-archivos",
  },
];

export default contents;
